name: Deploy Backend to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: duo-previa-backend
  REGION: us-central1 # Puedes cambiar la región si lo necesitas

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Write GCP Service Account Key'
        run: echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
        shell: bash

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: 'gcp-key.json'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Build and Deploy to Cloud Run'
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          # Puedes añadir más configuraciones aquí, como --platform managed, --allow-unauthenticated, etc.
          # Para permitir llamadas desde el frontend, probablemente necesites --allow-unauthenticated
          flags: --allow-unauthenticated
          working_directory: ./backend

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
